name: beize_vm
description: Virtual Machine of Beize.
version: 0.0.0

publish_to: none

environment:
    sdk: ">=3.0.0 <4.0.0"

dependencies:
    beize_shared:
        git:
            url: https://github.com/zyrouge/beize.git
            path: packages/beize_shared

dependency_overrides:
    beize_shared:
        path: ../beize_shared

dev_dependencies:
    zlint:
        git:
            url: https://github.com/zyrouge/dart_zlint.git
