name: outre
description: A highly dynamic multi-paradigm language.
version: 0.0.0

environment:
    sdk: ">=2.19.0-43.0.dev <3.0.0"

dependencies:
    meta: ^1.8.0
    path: ^1.8.0

dev_dependencies:
    lints: ^2.0.0
    test: ^1.16.0
    zlint:
        git:
            url: https://github.com/zyrouge/dart_zlint
