name: fubuki_compiler
description: Compiler of Fubuki.
version: 0.0.0

publish_to: none

environment:
    sdk: ">=2.18.0 <3.0.0"

dependencies:
    fubuki_vm:
        git:
            url: https://github.com/yukino-org/fubuki
            path: packages/fubuki_vm
    path: ^1.8.3

dependency_overrides:
    fubuki_vm:
        path: ../fubuki_vm

dev_dependencies:
    zlint:
        git:
            url: https://github.com/zyrouge/dart_zlint
