name: playground
description: Beize Playground
publish_to: none
version: 0.0.0

environment:
    sdk: ^3.7.0-209.1.beta

dependencies:
    beize_compiler:
        path: ../packages/beize_compiler
    beize_vm:
        path: ../packages/beize_vm
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter
    zlint:
        git:
            url: https://github.com/zyrouge/dart_zlint.git

flutter:
    uses-material-design: true
    fonts:
        - family: UbuntuMono
          fonts:
              - asset: assets/fonts/UbuntuMono-Regular.ttf
