name: outre_cli
description: A highly dynamic multi-paradigm language.
version: 0.0.0

publish_to: none

environment:
    sdk: ">=2.19.0-43.0.dev <3.0.0"

dependencies:
    args: ^2.3.1
    outre:
        path: ../
    path: ^1.8.0

dev_dependencies:
    lints: ^2.0.0
    zlint:
        git:
            url: https://github.com/zyrouge/dart_zlint
