name: Deploy

on:
    workflow_dispatch:

env:
    DEPLOY_BRANCH: gh-pages
    DEPLOY_DIR: dist
    GIT_CONFIG_NAME: "[Automated] Yui"
    GIT_CONFIG_EMAIL: yukino-org@users.noreply.github.com
    GIT_COMMIT_MSG: "[automated] deploy site (${{ github.sha }})"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-python@v4
              with:
                  python-version: 3.x

            - name: 🚧 Install dependencies
              run: pip install mkdocs-material

            - name: 👷 Build site
              run: mkdocs build -d docs-dist

            - name: 🚀 Deploy
              uses: zyrouge/gh-push-action@v1.0.5
              with:
                  directory: docs-dist
                  branch: gh-pages
